# Generated by Django 4.0.6 on 2022-08-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerPong', '0003_alter_beerpongrankingtable_games_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerpongrankingtable',
            name='games',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='beerpongrankingtable',
            name='rank',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='beerpongrankingtable',
            name='wins',
            field=models.IntegerField(default='0'),
        ),
    ]
